spring:

  datasource:

      username: root

      password: root@123

      url: jdbc:mysql://localhost:3306/testDemo

  jpa:

      hibernate:

        ddl-auto: update

      show-sql: true

      properties:

        hibernate:

          dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9000
